version: "3.7"

services:
  redis:
    container_name: ${CONTAINER_NAME_REDIS}
    image: redis:alpine
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - ${PORT_REDIS}:${PORT_REDIS}
    volumes:
      - ../redis.conf:/usr/local/etc/redis/redis.conf
  mongo:
    container_name: ${CONTAINER_NAME_MONGO}
    image: mongo
    restart: always
    mem_limit: "1000M"
    mem_reservation: "50M"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ../.docker/mongodb:/data/db
    ports:
      - ${PORT_MONGO}:${PORT_MONGO}
    networks:
      box_universe:
        ipv4_address: ${CONTAINER_MONGO_IP}
  node-server:
    container_name: ${CONTAINER_NAME_SERVER}
    restart: always
    mem_limit: "3000M"
    mem_reservation: "50M"
    build:
      context: ../
      dockerfile: ./server/docker/Dockerfile.prod
    environment:
      SECRET: ${SECRET}
      PORT: ${PORT_SERVER}
      SALT: ${SALT}
      TIME_EXPIRE_ACCESS_TOKEN: ${TIME_EXPIRE_ACCESS_TOKEN}
      TIME_EXPIRE_REFRESH_TOKEN: ${TIME_EXPIRE_REFRESH_TOKEN}
      MONGO_URL: ${MONGO_URL}
      AWS_S3_NAME_BUCKET: ${AWS_S3_NAME_BUCKET}
      AWS_S3_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID}
      AWS_S3_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY}
      NODE_ENV: production
    ports:
      - ${PORT_SERVER}:${PORT_SERVER}
    volumes:
      - ../server/dist/:/server/dist # production
    networks:
      box_universe:
        ipv4_address: ${CONTAINER_SERVER_IP}
    depends_on:
      - mongo
  node-client:
    container_name: ${CONTAINER_NAME_CLIENT}
    restart: always
    mem_limit: "3000M"
    mem_reservation: "50M"
    build:
      context: ../
      dockerfile: ./client/docker/Dockerfile.prod # production
    ports:
      - ${PORT_CLIENT}:${PORT_CLIENT}
    volumes:
      - ../client/.next/:/client/.next # production
    environment:
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      SECRET: ${SECRET}
      NEXTAUTH_SECRET: ${SECRET}
      FACEBOOK_CLIENT_ID: ${FACEBOOK_CLIENT_ID}
      FACEBOOK_CLIENT_SECRET: ${FACEBOOK_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      NODE_ENV: production
    networks:
      box_universe:
        ipv4_address: ${CONTAINER_CLIENT_IP}
    depends_on:
      - node-server
networks:
  box_universe:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${CONTAINER_SUBNET}
