apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  type: LoadBalancer
  externalIPs:
    - "172.26.22.88"
  selector:
    app: box-universe-mongo
  ports:
  - name: http
    protocol: TCP
    port: 27017
    targetPort: 27017