apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: LoadBalancer
  externalIPs:
    - "172.26.22.103"
  selector:
    app: box-universe-redis
  ports:
  - name: http
    protocol: TCP
    port: 6379
    targetPort: 6379                                                                                         